import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {recover} from './recover-url.mjs';
const origin='https://yandex-mail-readonly-synthetic.test.workers.dev';
const state={format:1,accountId:'11111111111111111111111111111111',workerName:'yandex-mail-readonly-synthetic',databaseName:'yandex-mail-synthetic',databaseId:'12345678-1234-1234-1234-123456789012',namespaceIds:['123','456'],stage:'worker-published',extra:'preserved'};
const closed=async url=>{assert.equal(url,origin);return Response.json({error:{code:'connection_not_configured'}},{status:503});};
async function fixture(fn,overrides={}){const cwd=await mkdtemp(path.join(tmpdir(),'url-recovery-test-'));await mkdir(path.join(cwd,'.local'));const file=path.join(cwd,'.local','setup-state.json');const original=JSON.stringify({...state,...overrides});await writeFile(file,original);try{await fn({cwd,file,original});}finally{await rm(cwd,{recursive:true,force:true});}}
test('checks closed Worker and preserves every field, with exact backup; idempotent',()=>fixture(async({cwd,file,original})=>{const result=await recover({origin,cwd,fetchImpl:closed});assert.equal(result.callback,origin+'/oauth/callback');assert.deepEqual(JSON.parse(await readFile(file,'utf8')),{...state,origin,stage:'bootstrap-complete'});const files=await readdir(path.dirname(file));const backup=files.find(x=>x.includes('before-url-recovery'));assert.equal(await readFile(path.join(path.dirname(file),backup),'utf8'),original);assert.equal((await recover({origin,cwd,fetchImpl:closed})).alreadyComplete,true);assert.equal((await readdir(path.dirname(file))).length,2);}));
test('wrong identity blocks before network or writes',()=>fixture(async({cwd,file,original})=>{await assert.rejects(()=>recover({origin,cwd,fetchImpl:()=>assert.fail('must not fetch')}));assert.equal(await readFile(file,'utf8'),original);assert.equal((await readdir(path.dirname(file))).length,1);},{workerName:'unrelated-worker'}));
test('network, wrong HTTP or unexpected body never changes state',async()=>{for(const fetchImpl of [async()=>{throw new Error('network');},async()=>Response.json({error:{code:'connection_not_configured'}},{status:500}),async()=>Response.json({error:{code:'rate_limit_unavailable'}},{status:503})])await fixture(async({cwd,file,original})=>{await assert.rejects(()=>recover({origin,cwd,fetchImpl}));assert.equal(await readFile(file,'utf8'),original);assert.equal((await readdir(path.dirname(file))).length,1);});});
test('concurrent state update is not overwritten',()=>fixture(async({cwd,file})=>{await assert.rejects(()=>recover({origin,cwd,fetchImpl:async()=>{await writeFile(file,'changed');return closed(origin);}}));assert.equal(await readFile(file,'utf8'),'changed');}));
test('mismatched existing origin and malformed resource IDs never fetch',async()=>{for(const overrides of [{origin:'https://yandex-mail-readonly-different.test.workers.dev'},{accountId:'invalid'},{databaseId:'invalid'}])await fixture(async({cwd,file,original})=>{await assert.rejects(()=>recover({origin,cwd,fetchImpl:()=>assert.fail('must not fetch')}));assert.equal(await readFile(file,'utf8'),original);},overrides);});
test('missing, foreign, non-HTTPS or path-bearing recovery origins are rejected',async()=>{for(const supplied of [undefined,'http://yandex-mail-readonly-synthetic.test.workers.dev','https://other.test.workers.dev',origin+'/path'])await fixture(async({cwd,file,original})=>{await assert.rejects(()=>recover({origin:supplied,cwd,fetchImpl:()=>assert.fail('must not fetch')}));assert.equal(await readFile(file,'utf8'),original);});});
